### ISSUE TITLE
Running sample provides no output ?

### ISSUE THREAD

**Issue by writeameer** [engineerd/kubecontroller-csharp#2]
Hi there Radu,

Firstly let me say this is very interesting and thank you for sharing. I've created the CRD and the sample CR in the project. Creating new `Example` resources or deleting them doesn't seem to generate any event or output when running:

```
dotnet run KubeController.Sample/
```

How can I see output for the events generated ? Thanks again for sharing and would appreciate any guidance.

**Comment by radu-matei** [comment]
Hey!
First of all, apologies for missing this, the week of KubeCon has been crazy.

This is interesting, what versions of: .NET Core and Kubernetes are you running?
Also, if you modify the sample not to start the controller, but say, list all CRs available, would that work?

**Comment by writeameer** [comment]
Hi there Radu,

Thanks so much for getting back to me. This is a very interesting project of yours and look forward to working with it more. I'm using dotnet version:

```
dotnet --version
3.0.100-preview-009812
```
With Kubernetes version:

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

And the following code:

```
            var config = KubernetesClientConfiguration.BuildDefaultConfig();
            IKubernetes client = new Kubernetes(config);

            var crds = client.ListCustomResourceDefinition();

            foreach(var item in crds.Items) {
                
                Console.WriteLine($"Name:{item.Metadata.Name}");
                Console.WriteLine($"Group:{item.Spec.Group}");
                Console.WriteLine($"Scope:{item.Spec.Scope}");
                Console.WriteLine($"Version:{item.Spec.Version}");
                
            }
```

Provides the following output:

```
Name:examples.engineerd.dev
Group:engineerd.dev
Scope:Namespaced
Version:v1alpha1
```

Look forward to your thoughts.

**Comment by radu-matei** [comment]
Yeah, all the libraries here have been tested with .NET Core 2.2, not with 3.0, and I'm not sure I'll have the bandwidth to try out porting to .NET Core 3.0 in the next month at least.

That being said, let me know if it works if you try out 2.2, and if you start trying to port to 3.0, let me know if I can help.

Thanks!

**Comment by writeameer** [comment]
Hi there Radu,

Thank and understood - let me stick to what's been tested to start with. I using `dotnet 2.2.106`  from my mac:

```
$ dotnet --version
2.2.106
```

And k8s running on AKS (1.12):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
What I tried was basically create the following CRD and then delete it:

```
apiVersion: "engineerd.dev/v1alpha1"
kind: Example
metadata:
  name: my-cr-example3
spec:
  exampleType: "controller"
  programmingLanguage: "csharp"
```

I can see the example:

```
kubectl get example
NAME             KIND
my-cr3-example   Example.v1alpha1.engineerd.dev
```

I assumed while deleting the above `example` resource , I might see some output. I see nothing - am I testing this wrong ?

**Comment by radu-matei** [comment]
Just as a side note, the `kubectl` version is somewhat behind, you should probably get a newer version - that being said, I don't think it's the reason for your issue.

I think the main issue in this case is that you're not listening on the right namespace - make sure you have the correct namespace when listening, and you create resources in the same one:

```
$ kubectl cluster-info
Kubernetes master is running at https://localhost:6445
KubeDNS is running at https://localhost:6445/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
radu:KubeController.Sample$ kubectl create ns kubecontroller
namespace/kubecontroller created
radu:KubeController.Sample$ kubectl create -f deploy/crd.yaml
customresourcedefinition.apiextensions.k8s.io/examples.engineerd.dev created
radu:KubeController.Sample$ dotnet build
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.97 ms for /mnt/c/projects/go/src/github.com/engineerd/kubecontroller-csharp/KubeController.Sample/KubeController.Sample.csproj.
  Restore completed in 55.97 ms for /mnt/c/projects/go/src/github.com/engineerd/kubecontroller-csharp/KubeController/KubeController.csproj.
  KubeController -> /mnt/c/projects/go/src/github.com/engineerd/kubecontroller-csharp/KubeController/bin/Debug/netstandard2.0/KubeController.dll
  KubeController.Sample -> /mnt/c/projects/go/src/github.com/engineerd/kubecontroller-csharp/KubeController.Sample/bin/Debug/netcoreapp2.2/KubeController.Sample.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.46
radu:KubeController.Sample$ dotnet run


Event type: Added for my-cr-example2
```

Just ran again, and everything seems to work properly (at least for .NET Core 2.2.203).

Let me know if this helps!

**Comment by writeameer** [comment]
Hi there Radu,

Thank you and man I feel stupid :). Just noticed this as you mentioned it:

https://github.com/engineerd/kubecontroller-csharp/blob/master/KubeController.Sample/Program.cs#L20

```
 Namespace = "kubecontroller"
```
Yes - I was just working on `default`. This thing works like a charm:

```
Event type: Added for my-cr3-example
Event type: Added for my-cr3-example
Event type: Added for my-cr3-example
Event type: Added for my-cr3-example
```


Thanks so much. This is an interesting project indeed ! And to answer your question in your [blog](https://radu-matei.com/blog/kubernetes-controller-csharp/) : "Would you like to see this as a NuGet package? " - most definitely !

**Comment by radu-matei** [comment]
Glad you have the sample working now, and thanks for the feedback - let me know what other things you'd like to see in a package for a .NET controller.

Thanks!
